---
title: "Assignment 1: Introduction"
author: Aislinn McL.
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have started using R with my research on water utility rate structures and affordability with Lauren Patterson. Right now she sends me blocks of code to help me make different calculations, so I'm not writing any myself. I use GitHub Desktop to track changes, but have really only done commit/push since I am just updating excel files. I also have some experience in Excel from my work as an analyst at a tech company before I came to Duke.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident that I can learn all of this! But not confident in that I don't know how to do any of it yet.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I suppose the one thing I always get nervous about is making an unfixable mistake that affects other people's work, so it was nice to hear that we can't push anything upstream.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/aislinnmcl/Environmental_Data_Analytics_2021.git


